pipeline {
        agent any
        tools{
                maven 'maven'
        }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn deploy sonar:sonar'
            }
        }
        
        }
        post{
                success{
                        emailext attachLog: true, body: 'pipeline success', recipientProviders: [buildUser()], subject: 'success', to: 'samhithaaluri@gmail.com'
                }
                failure{
                        emailext attachLog: true, body: 'pipeline failed', recipientProviders: [buildUser()], subject: 'failed', to: 'samhithaaluri@gmail.com'
                }
        }

    }


