pipeline {
        agent any
        tools{
                maven 'maven'
        }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn deploy sonar:sonar'
            }
        }
        
        }
        post{
                failure{
                        emailext body: 'Your pipeline is failed', subject: 'failed', to: 'samhithaaluri@gmail.com'
                }
        }

    }


